DROP TABLE IF EXISTS friendship CASCADE;
DROP TABLE IF EXISTS films_genres CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS mpa CASCADE;
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS directors CASCADE;
DROP TABLE IF EXISTS film_director CASCADE;

CREATE TABLE IF NOT EXISTS mpa (
  id integer  generated by default as identity PRIMARY KEY,
  name varchar(255) not null
);

CREATE TABLE IF NOT EXISTS genres (
  id integer generated by default as identity PRIMARY KEY,
  name varchar(255) not null
);

CREATE TABLE IF NOT EXISTS users (
  id integer generated by default as identity PRIMARY KEY,
  login varchar(255) not null,
  email varchar(255) not null,
  name varchar(255) not null,
  birthday date not null
);

CREATE TABLE IF NOT EXISTS films (
  id integer generated by default as identity PRIMARY KEY,
  name varchar(255) not null,
  description varchar(255) not null,
  releaseDate date not null,
  duration integer not null,
  mpa_id integer not null REFERENCES mpa(id)
);

CREATE TABLE IF NOT EXISTS likes (
  users_id integer not null REFERENCES users(id) on delete cascade,
  films_id integer not null REFERENCES films(id) on delete cascade
);

CREATE TABLE IF NOT EXISTS films_genres (
  films_id integer not null REFERENCES films(id) on delete cascade,
  genres_id integer not null REFERENCES genres(id) on delete cascade
);

CREATE TABLE IF NOT EXISTS friendship (
  users_id integer not null REFERENCES users(id) on delete cascade,
  friends_id integer not null REFERENCES users(id) on delete cascade,
  confirmed boolean not null
);

CREATE TABLE IF NOT EXISTS directors (
  director_id integer generated by default as identity PRIMARY KEY,
  name varchar(255) not null
  );

CREATE TABLE IF NOT EXISTS film_director (
  film_id     integer not null REFERENCES films(id) on delete cascade,
  director_id integer not null REFERENCES directors(director_id) on delete cascade
);